# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\"\n\x0fServeClientArgs\x12\x0f\n\x07request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\"a\n\x10VoteRequestReply\x12\x0e\n\x06nodeId\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x1e\n\x16leaseDurationRemaining\x18\x04 \x01(\x02\"Y\n\x0eGetVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06nodeId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"N\n\x10\x41ppendEntryReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\x12\x0e\n\x06nodeId\x18\x04 \x01(\x05\"T\n\x0fLogRequestReply\x12\x0e\n\x06nodeId\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\x12\x0f\n\x07success\x18\x04 \x01(\x08\"%\n\x07\x43ommand\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"3\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x19\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x08.Command\"\xaf\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.LogEntry\x12\x19\n\x11leaderCommitIndex\x18\x06 \x01(\x05\x12\x15\n\rleaseDuration\x18\x07 \x01(\x05\x32\xb8\x01\n\x08RaftNode\x12\x34\n\x0bServeClient\x12\x10.ServeClientArgs\x1a\x11.ServeClientReply\"\x00\x12<\n\x0fServeLogRequest\x12\x15.AppendEntriesRequest\x1a\x10.LogRequestReply\"\x00\x12\x38\n\x10ServeVoteRequest\x12\x0f.GetVoteRequest\x1a\x11.VoteRequestReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVECLIENTARGS']._serialized_start=14
  _globals['_SERVECLIENTARGS']._serialized_end=48
  _globals['_SERVECLIENTREPLY']._serialized_start=50
  _globals['_SERVECLIENTREPLY']._serialized_end=117
  _globals['_VOTEREQUESTREPLY']._serialized_start=119
  _globals['_VOTEREQUESTREPLY']._serialized_end=216
  _globals['_GETVOTEREQUEST']._serialized_start=218
  _globals['_GETVOTEREQUEST']._serialized_end=307
  _globals['_APPENDENTRYREPLY']._serialized_start=309
  _globals['_APPENDENTRYREPLY']._serialized_end=387
  _globals['_LOGREQUESTREPLY']._serialized_start=389
  _globals['_LOGREQUESTREPLY']._serialized_end=473
  _globals['_COMMAND']._serialized_start=475
  _globals['_COMMAND']._serialized_end=512
  _globals['_LOGENTRY']._serialized_start=514
  _globals['_LOGENTRY']._serialized_end=565
  _globals['_APPENDENTRIESREQUEST']._serialized_start=568
  _globals['_APPENDENTRIESREQUEST']._serialized_end=743
  _globals['_RAFTNODE']._serialized_start=746
  _globals['_RAFTNODE']._serialized_end=930
# @@protoc_insertion_point(module_scope)
